### ISSUE TITLE
AD001/AD002: Server 2008 FFL not required for Exchange 2013

### ISSUE THREAD

**Issue by JetzeMellema** [cunninghamp/ExchangeAnalyzer#34]
The DFL and FFL checks in AD001 and AD002 shouldn't result in a fail when no Exchange 2016 servers have been found. Exchange 2013 required Server 2003 FFL, Server 2016 requires Server 2008 FFL or newer.

**Comment by damianscoles** [comment]
Changes added to address this. If Exchange 2013 alone is detected, Windows 2003+ Forest / Domain levels will be expected..  If Exchange 2016 is detected, Windows 2008+ Forest / Domain levels will be expected.
