### ISSUE TITLE
Consider a 3rd result category: Informative

### ISSUE THREAD

**Issue by JetzeMellema** [cunninghamp/ExchangeAnalyzer#36]
I think we need to work with a 3rd result category for Informative results. An example is EXSRV001 which could have three results:
- All servers 2010 or older: Fail
- All servers 2013 or newer: Pass
- One or more 2010 or older, as well as one or more 2013 or newer: Information: pre-2013 servers are not included in the report.

In fact we may even use Error, Warning and Information just as the old BPA did.

**Comment by cunninghamp** [comment]
In discussions about this, looking at implementing Passed, Failed, Warning, and Info as test outcomes. Also looking at removing the list of passed/failed objects, and consolidating that information into the Comments section of each line item to make better use of space, and provide clearer output.

**Comment by cunninghamp** [comment]
This has been implemented in a new test format, and merged to development branch.
