### ISSUE TITLE
Report file name should include date and time

### ISSUE THREAD

**Issue by cunninghamp** [cunninghamp/ExchangeAnalyzer#37]
Append the date and time to the report file name so that reports are preserved and can be compared.

eg, instead of

ExchangeAnalyzerReport.html

use

ExchangeAnalyzerReport-20160117-0930.html

Suggested by Jeff Gullet. Should be easy to implement, I have some code from another script that will do this.

**Comment by chrisbrownie** [comment]
It would be good to accept a parameter (-ReportFile?) that allows the administrator to specify an output path for the html file. This would make the script a lot easier for anyone who may want to automate it and have it written out to a UNC share for monitoring systems and the like.

**Comment by cunninghamp** [comment]
@chrisbrownie agreed.

A non-mandatory parameter with no default value:

```
    [Parameter( Mandatory=$false)]	
    [string]$FileName,
```

Then, if no report file specified by user, calculate a unique report file name based on time and date. Code re-use FTW, this was written years ago for Get-Mailboxreport.ps1

```
#If no filename specified, generate report file name with random strings for uniqueness
#Thanks to @proxb and @chrisbrownie for the help with random string generation

if ($filename)
{
	$reportfile = $filename
}
else
{
	$timestamp = Get-Date -UFormat %Y%m%d-%H%M
	$reportfile = "$($myDir)\ExchangeAnalyzerReport-$($timestamp).html"
}
```

**Comment by cunninghamp** [comment]
Chris has submitted a PR for this.

**Comment by cunninghamp** [comment]
This improvement has been merged to development branch.
