### ISSUE TITLE
Proposed wiki-based documentation standard

### ISSUE THREAD

**Issue by cunninghamp** [cunninghamp/ExchangeAnalyzer#41]
Tests.xml contains a reference URL for each test for more info. The wiki page listing the tests also contains a reference URL.

I propose the URLs be standardize to point to Wiki pages. The Wiki pages for each test can then be edited and improved over time to clarify and explain tests without having to make changes to the data in Tests.xml, avoiding issues where one person's copy of Tests.xml has a better reference URL than an older copy.

The Wiki pages can be a jump-off point for even more detailed information. For example, if you write a long tutorial or a script that is useful for responding to that test result, or there are multiple TechNet pages that reinforce that best practice, then link to them all from the wiki page for that test.

A proposed template is here:
https://github.com/cunninghamp/ExchangeAnalyzer/wiki/TESTID

To prevent the "Pages" list in the sidebar of the wiki from getting out of hand we can add a custom sidebar with a hierarchical menu-style list to help with navigation.

**Comment by cunninghamp** [comment]
@bdesmond @Mike-Crowley @damianscoles @swngdnz any input on this change? I've marked it for inclusion in the next release milestone. Minimal work required to make it happen at this early stage.

**Comment by bdesmond** [comment]
I would add an Applies To section. Otherwise looks fine to me, should say that for a test to be checked in, there has to be an accompanying wiki page.

Thanks,
Brian Desmond

**Comment by swngdnz** [comment]
I think it’s a good idea.

**Comment by Mike-Crowley** [comment]
Sounds good. As you implied, that allows the test author to manage the conversation vs dumping the user on a potentially dry technet page.

**Comment by cunninghamp** [comment]
@damianscoles mate can you please do the wiki pages for AD001 and AD002. I have pasted in the template and you can also look at the other ones I've already written.
