### ISSUE TITLE
Run-AD001 Should Not Do String Comparisons

### ISSUE THREAD

**Issue by bdesmond** [cunninghamp/ExchangeAnalyzer#46]
In the test's current state, it is going to need to be updated every single time a new AD DFL/FFL is introduced. Instead, it should be testing the actual values on a >= basis:

1. DFL, connect to RootDSE and check the domainFunctionality attribute on one DC in each domain
2. FFL, connect to RootDSE and check the forestFunctionality attribute on one DC in the forest

Here are the values: https://msdn.microsoft.com/en-us/library/cc223742.aspx

**Comment by damianscoles** [comment]
Fixed.  Querying domains via RootDSE.  Added to both AD001 and AD002.
