### ISSUE TITLE
Script throws error due to Split method

### ISSUE THREAD

**Issue by cunninghamp** [cunninghamp/ExchangeAnalyzer#62]
Reported by a user, no repro yet. Awaiting a reply from them. Can look at removing the Split method and using another way to achieve the same thing.

```
[PS] C:\scripts\ExchangeAnalyzer-0.1.1-Beta.2>.\Run-ExchangeAnalyzer.ps1
Vector smash protection is enabled.
Method invocation failed because [Microsoft.Exchange.Data.Directory.ADObjectId] does not contain a method named
‘Split’.
At C:\scripts\ExchangeAnalyzer-0.1.1-Beta.2\Run-ExchangeAnalyzer.ps1:308 char:80
+ Server: $($server.Name), Site: $(( …
+ ~
+ CategoryInfo : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : MethodNotFound
```

**Comment by swngdnz** [comment]
Generally a $obj.ToString().Split() takes care of it…

**Comment by weeyin83** [comment]
Also getting this issue when I run the script on Server 2012 R2/Exchange 2013

**Comment by cunninghamp** [comment]
@weeyin83 can you please try the script in this Zip, which might fix the issue:

https://github.com/cunninghamp/ExchangeAnalyzer/archive/Fix-Issue-62.zip

**Comment by weeyin83** [comment]
@cunninghamp Thanks Paul, unfortunately still the same error. 

> Method invocation failed because [Microsoft.Exchange.Data.Directory.ADObjectId] does not contain a method named
'Split'.
At C:\Analyzer\Run-ExchangeAnalyzer.ps1:371 char:80
+                             <th colspan=""3"">Server: $($server.Name), Site: $(( ...
+                                                                                ~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [Microsoft.Exchange.Data.Directory.ADObjectId] does not contain a method named
'Split'.
At C:\Analyzer\Run-ExchangeAnalyzer.ps1:371 char:80
+                             <th colspan=""3"">Server: $($server.Name), Site: $(( ...
+                                                                                ~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

>

**Comment by cunninghamp** [comment]
@weeyin83 can you please send me an email to feedback@exchangeanalyzer.com, I'd like to get some info about your environment so I can get a better understanding of why this works in some environments and not others.

**Comment by cunninghamp** [comment]
Okay I’ve worked it out.

Original code works fine in EX2016, but not EX2013.

A fix suggested by @swngdnz via email fix works fine in EX2013, but not EX2016.

Get-ExchangeServer returns different types depending on the version. One is a System.String, the other is a Microsoft.Exchange.Data.Directory.ADObjectId.

Should be able to cater for both, no problem. Stay tuned!

**Comment by cunninghamp** [comment]
Fix is in, if anyone is able to test by downloading the files here:

https://github.com/cunninghamp/ExchangeAnalyzer/archive/Fix-Issue-62.zip

**Comment by weeyin83** [comment]
@cunninghamp Now running successfully, thanks!

**Comment by cunninghamp** [comment]
@weeyin83 terrific, thank you for testing that. The fix will be included in the next release then.

**Comment by cunninghamp** [comment]
Fix merged to development branch.
