### ISSUE TITLE
Exchange build number test hangs if IEESC is enabled

### ISSUE THREAD

**Issue by cunninghamp** [cunninghamp/ExchangeAnalyzer#86]
Reported in a field test. Need to repro.

**Comment by damianscoles** [comment]
Confirmed on a Windows 2012 R2 and Windows 2008 R2 server with IE ESC is enabled.  The pop-up has an issue with these sites:

about:security_powershell.exe
about://c.webtrends.com/acs/account/mx643kesn3/js/wt.js
https://i2-technet.sec.s-msft.com
https://i3.services.social.microsoft.com
https://ajax.aspnetcdn.com
about://m.webtrends.com/dcsjwb9vb00000c932fd0rjc7_5p3t/wtid.js
about:blank

**Comment by swngdnz** [comment]
### ESC = Enhanced Security Configuration

$adminKey = 'HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}'
$userKey  = 'HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}'

function Change-IE-Esc   ### should be a 'private' function
{
               Param(
                              [int] $OnOrOff
               )
               ## if param is 1 -- turn it on
               ## if param is 0 -- turn it off

               wv "*** Enter Change-IE-Esc: OnOrOff $OnOrOff"

               Set-ItemProperty -Path $adminKey -Name 'IsInstalled' -Value $OnOrOff -Force
               Set-ItemProperty -Path $userKey  -Name 'IsInstalled' -Value $OnOrOff -Force

               Stop-Process -Name Explorer -Force

               wv '*** Exit Change-IE-Esc'
}

function Disable-IE-Esc
{
               wv '*** Enter Disable-IE-Esc'

               Change-IE-Esc 0

               wv '*** Exit Disable-IE-Esc'
}

function Enable-IE-Esc
{
               wv '*** Enter Enable-IE-Esc'

               Change-IE-Esc 1

               wv '*** Exit Enable-IE-Esc'
}

**Comment by cunninghamp** [comment]
@swngdnz do you think we should add functionality to enable/disable ESC, or simply flag that it was the reason the script couldn't fetch build numbers?

My thinking is, Exchange Analyzer currently does a lot of information retrieval, but makes no changes to the environment. Later this might be beneficial to minimize the permissions required to run it.

**Comment by bdesmond** [comment]
Definitely wouldn’t recommend making any changes.

Personally I think we should can this whole flow in favor of an input file. The overhead to update it every quarter is very minimal.

**Comment by chrisbrownie** [comment]
Tend to agree with @bdesmond here. I work with a bunch of Exchange environments that under no circumstances will permit internet access, which makes running this script problematic.

Perhaps a simple warning at the top of the output file may assist with keeping the file up to date: "Warning: your Exchange metadata file is over 60 days old and may be out of date. Please update metadata.xml as soon as possible to ensure this script's results are current."

The script could even, potentially, have a switch or trigger to automatically update the metadata file if possible.

**Comment by cunninghamp** [comment]
Ok, it's also the slowest test in the tool at the moment, so let's ditch it in favour of a local file. Can always revert back to scraping later. I don't think we will though, if a local file is well implemented. It solves may problems (proxies, slow speed, IE ESC).

Flagging the age of the metadata file itself will be inaccurate. A 60 day old file might be 100% up to date, yet a 2 day old file might be out of date if Microsoft released quarterly updates 1 day ago. So I think the metadata file needs to have something in it that states the last date that Microsoft released quarterly updates (looks like they'll be keeping 2013/2016 CU's on a synchronized release schedule), and if that date is +90 days ago, advise the user to download the latest file.

Does that sound like it will be an effective way forward?

**Comment by swngdnz** [comment]
Should we test and say “IE ESC is enabled – metadata may be out of date”

**Comment by cunninghamp** [comment]
Branch: https://github.com/cunninghamp/ExchangeAnalyzer/tree/Fix-Issue-86

Added static, local XML file containing build number data. If server has a build number not found in the file, the report will flag it as a warning and "not found in XML". The Wiki page will be updated to instruct user to download latest Exchange Analyzer to fix.

It means generating a new XML file each time Microsoft releases new builds, but that only takes a few seconds using the same TechNet HTML scraping code, just piping the results to Export-Clixml.
